package Strings is
    Add_Height : constant String := "+h";
    Add_Width : constant String := "+w";
    Back : constant String := "Back";
    Cancel : constant String := "Cancel";
    Create : constant String := "New";
    Create_Map : constant String := "Create";
    Done : constant String := "Done";
    Edit : constant String := "Edit";
    Help : constant String := "Help";
    Host : constant String := "Host";
    Join : constant String := "Join";
    Name_Hint : constant String := "Enter Map Name";
    Next : constant String := ">";
    Prev : constant String := "<";
    Quit : constant String := "Quit";
    Save : constant String := "Save";
    Solo : constant String := "Solo";
    Sub_Height : constant String := "-h";
    Sub_Width : constant String := "-w";
    X : constant String := "x";
    Room_Name : constant String := "Room Name";
end Strings;
